### ISSUE TITLE
Project needs help?

### ISSUE THREAD

**Issue by rubemlrm** [go-faker/faker#43]
Hello to everyone.

First and foremost thank you for the hard work that has been done on this project. I've been using this in some projects and it's working very well.

Despite this, I made a PR a few weeks ago and didn't have feedback relative to that PR besides the PR that I've made, I saw some other PR and issues without much feedback, and because of this raised in my head that this project may need some external help to avoid the dead of this project.

So considering this @bxcodec and the rest of the team, which are the main ideas for this project? do you need help from the community? I would like to avoid seeing dozens of forks for this project and instead see this project growing up.

Cheers

P.S: This is not the typical ETA issue asking for deadlines for new features, this Is an open-source project, made by the community for community.

**Comment by bxcodec** [comment]
Hi @rubemlrm ,

Yes, I think most of the maintainers have full-time jobs. I am aware it's been lacking support recently. 
Any help is appreciated.

I will gladly onboard new maintainers if anyone can commit to reviewing and doing releases.

Do you think you'll be able to do this? I don't have a proper way for onboarding, but I will seek your understanding of what I can do to help you onboard and be the maintainers.

Thanks

**Comment by rubemlrm** [comment]
Hi @bxcodec

I can try help you guys with this project, it was like I was saying this is a project that I use in others projects.

Cheers

**Comment by bxcodec** [comment]
Hi @rubemlrm , 

I have invited you to be on of the maintainer team.
Let me know if you need anything to help you onboard.
Thakns
