### ISSUE TITLE
About interface{} type suggestion

### ISSUE THREAD

**Issue by MrGuoRanDuo** [go-faker/faker#48]
I dont care what's exactlly type it is. I just fucking want a fake value 1 "abcabc" and so on.
what's wrong with you guys. it's faker lib.uh?  why you want's to find out type???
give me fucking option to gen interface() value!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by rubemlrm** [comment]
Hello @MrGuoRanDuo 

Try not to be so offensive with something that is an open source project where the developers give some of their time to provide a new tool.
I know that can be a limitation of this project, but can you provide a good use case example for your problem?

**Comment by bxcodec** [comment]
I'm closing this. Any PR is welcome. We appreciate the idea, but show me the code :)
