### ISSUE TITLE
Deprecate the old module

### ISSUE THREAD

**Issue by karelbilek** [go-faker/faker#8]
Please, deprecate the old module, if any new development will happen on this one.

Many people, me included, did not know about this repo (the old repo has 4k stars, this one 40).

**Comment by karelbilek** [comment]
If you mark the old one as deprecated, `go vet` and other tools will mark it as such.

**Comment by bxcodec** [comment]
Okay, I totally missed this

**Comment by karelbilek** [comment]
The latest commit is good, but I'm not sure if it wouldn't be worth it to also create a tagged release with the deprecation. So it appears when people install with @latest.

**Comment by bxcodec** [comment]
Oh shoot. I didn't know that. I'll released new version on the old one

**Comment by karelbilek** [comment]
thx!

**Comment by karelbilek** [comment]
Seems like you removed it again? :) I don't see the deprecation warning anymore.

you probably had a reason to do that, I guess

**Comment by bxcodec** [comment]
@karelbilek  
Nope, I didn't remove it. Weird...
Is the warning still not exist yet?
