### ISSUE TITLE
could this support deterministic random values?

### ISSUE THREAD

**Issue by adu-crypto** [go-faker/faker#9]
could I specify the randomness source and get deterministic random values?

**Comment by wolf-joe** [comment]
> Right now, we use a global var for the randomness source. @wolf-joe please chime in, is it possible to support this?

Maybe we can pass a seed number to those generate functions by options, but making the seed number work everywhere is difficult.

**Comment by adu-crypto** [comment]
How about letting these generators share the same seed number?
this should be helpful for detecting determinism issues
